nombre= input("Ingresa tu nombre: ")
apellido= input("Ingresa tu apellido: ")
edad= int (input ("Ingresa tu edad: "))
correo= input("Ingresa tu correo: ")
telefono= input("Ingresa tu telefono: ")

print ("Nombre: " + nombre)
print ("Apellido: " + apellido)
print ("Tengo: " +str(edad) + "años")
print ("Correo: " + correo)
print ("Telefono: " + telefono)